/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ActivitySource {
    /** Slug for designated source */
    slug: string;
    /** Name of source of information */
    name: string;
    /** URL for source logo */
    logo: string;
}
