/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Vital } from "@fern-api/vital";

export interface ClientActivityResponse {
    activity: Vital.ClientFacingActivity[];
}
