/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { VitalApi } from "@fern-api/vital";

export interface RawActivity {
    /** Provider */
    source: VitalApi.ActivitySource;
    priorityId: VitalApi.PriorityId;
    sourceId: VitalApi.SourceId;
    userId: VitalApi.UserId;
    providerId: VitalApi.ProviderId;
    timestamp: Date;
    data?: VitalApi.ActivityData;
}
