/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { VitalApi } from "@fern-api/vital";

export interface RawActivity {
    id: string;
    /** Provider */
    source?: VitalApi.Source;
    priorityId: VitalApi.PriorityId;
    sourceId: VitalApi.SourceId;
    userId: VitalApi.UserId;
    providerId: VitalApi.ProviderId;
    timestamp: Date;
    data: Record<string, string>;
}
