/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { VitalApi } from "@fern-api/vital";

export interface RawActivitySummaryResponse {
    activity: VitalApi.RawActivity[];
}
