/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Vital } from "@fern-api/vital";

export interface RawActivity {
    id: string;
    /** Provider */
    source?: Vital.Source;
    priorityId: Vital.PriorityId;
    sourceId: Vital.SourceId;
    userId: Vital.UserId;
    providerId: Vital.ProviderId;
    timestamp: Date;
    data: Record<string, string>;
}
