/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { VitalApi } from "@fern-api/vital";
import * as core from "../../../../core";

export const ActivityData: core.serialization.ObjectSchema<serializers.ActivityData.Raw, VitalApi.ActivityData> =
    core.serialization.object({
        data: core.serialization.string(),
    });

export declare namespace ActivityData {
    interface Raw {
        data: string;
    }
}
