/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { VitalApi } from "@fern-api/vital";
import * as core from "../../../../core";

export const ActivitySummaryResponse: core.serialization.ObjectSchema<
    serializers.ActivitySummaryResponse.Raw,
    VitalApi.ActivitySummaryResponse
> = core.serialization.object({
    activity: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("../../..")).ActivitySummary)
    ),
});

export declare namespace ActivitySummaryResponse {
    interface Raw {
        activity: serializers.ActivitySummary.Raw[];
    }
}
