/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { VitalApi } from "@fern-api/vital";
import * as core from "../../../../core";

export const ActivitySource: core.serialization.ObjectSchema<serializers.ActivitySource.Raw, VitalApi.ActivitySource> =
    core.serialization.object({
        slug: core.serialization.string(),
        name: core.serialization.string(),
        logo: core.serialization.string(),
    });

export declare namespace ActivitySource {
    interface Raw {
        slug: string;
        name: string;
        logo: string;
    }
}
