/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { VitalApi } from "@fern-api/vital";
import * as core from "../../../../core";

export const ClientActivityResponse: core.serialization.ObjectSchema<
    serializers.ClientActivityResponse.Raw,
    VitalApi.ClientActivityResponse
> = core.serialization.object({
    activity: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("../../..")).ClientFacingActivity)
    ),
});

export declare namespace ClientActivityResponse {
    interface Raw {
        activity: serializers.ClientFacingActivity.Raw[];
    }
}
