/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Vital } from "@fern-api/vital";
import * as core from "../../../../core";

export const ClientFacingActivity: core.serialization.ObjectSchema<
    serializers.ClientFacingActivity.Raw,
    Vital.ClientFacingActivity
> = core.serialization.object({
    source: core.serialization.lazyObject(async () => (await import("../../..")).Source),
    date: core.serialization.string(),
    userId: core.serialization.property(
        "user_id",
        core.serialization.lazy(async () => (await import("../../..")).UserId)
    ),
    userKey: core.serialization.property("user_key", core.serialization.string().optional()),
    caloriesTotal: core.serialization.property("calories_total", core.serialization.number().optional()),
    caloriesActive: core.serialization.property("calories_active", core.serialization.number().optional()),
    steps: core.serialization.number().optional(),
    dailyMovement: core.serialization.property("daily_movement", core.serialization.number().optional()),
    low: core.serialization.number().optional(),
    medium: core.serialization.number().optional(),
    high: core.serialization.number().optional(),
    floorsClimbed: core.serialization.property("floors_climbed", core.serialization.number().optional()),
    timezoneOffset: core.serialization.property("timezone_offset", core.serialization.number().optional()),
});

export declare namespace ClientFacingActivity {
    interface Raw {
        source: serializers.Source.Raw;
        date: string;
        user_id: serializers.UserId.Raw;
        user_key?: string | null;
        calories_total?: number | null;
        calories_active?: number | null;
        steps?: number | null;
        daily_movement?: number | null;
        low?: number | null;
        medium?: number | null;
        high?: number | null;
        floors_climbed?: number | null;
        timezone_offset?: number | null;
    }
}
