/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const VitalEnvironment = {
    UsProduction: "https://api.tryvital.io/",
    EuProduction: "https://api.eu.tryvital.io",
    UsSandbox: "https://api.sandbox.tryvital.io",
    EuSandbox: "https://api.sandbox.eu.tryvital.io",
} as const;

export type VitalEnvironment =
    | typeof VitalEnvironment.UsProduction
    | typeof VitalEnvironment.EuProduction
    | typeof VitalEnvironment.UsSandbox
    | typeof VitalEnvironment.EuSandbox;
