/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const VitalApiEnvironment = {
    UsProduction: "https://api.tryvital.io/",
    EuProduction: "https://api.eu.tryvital.io",
    UsSandbox: "https://api.sandbox.tryvital.io",
    EuSandbox: "https://api.sandbox.eu.tryvital.io",
} as const;

export type VitalApiEnvironment =
    | typeof VitalApiEnvironment.UsProduction
    | typeof VitalApiEnvironment.EuProduction
    | typeof VitalApiEnvironment.UsSandbox
    | typeof VitalApiEnvironment.EuSandbox;
