/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const VitalApiEnvironment = {
    Production: "https://api.tryvital.io/v2",
} as const;

export type VitalApiEnvironment = typeof VitalApiEnvironment.Production;
