/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { VitalApi } from "@fern-api/vital";
import * as core from "../../../../core";

export const PriorityId: core.serialization.Schema<serializers.PriorityId.Raw, VitalApi.PriorityId> =
    core.serialization.number();

export declare namespace PriorityId {
    type Raw = number;
}
