/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Vital } from "@fern-api/vital";
import * as core from "../../../../core";

export const Source: core.serialization.ObjectSchema<serializers.Source.Raw, Vital.Source> = core.serialization.object({
    slug: core.serialization.string(),
    name: core.serialization.string(),
    logo: core.serialization.string(),
});

export declare namespace Source {
    interface Raw {
        slug: string;
        name: string;
        logo: string;
    }
}
