/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Vital } from "@fern-api/vital";
import * as core from "../../../../core";

export const SourceId: core.serialization.Schema<serializers.SourceId.Raw, Vital.SourceId> =
    core.serialization.number();

export declare namespace SourceId {
    type Raw = number;
}
